stages:
  - docker
  - deploy

docker_job:
  stage: docker
  image: docker:stable

  services:
    - docker:dind

  only:
    - master

  tags:
    - docker

  artifacts:
    paths:
      - build

  before_script:
    - docker login --username "$(printenv GITLAB_USERNAME)" --password "$(printenv GITLAB_PASSWORD)" registry.styleschool.ru

  script:
    - docker build --tag "$(printenv GITLAB_REPOSITORY):latest" ./
    - docker push "$(printenv GITLAB_REPOSITORY):latest"

deploy_job:
  stage: deploy

  only:
    - master

  tags:
    - hetzner

  before_script:
    - docker rm --force "$(printenv CONTAINER_NAME)"
    - docker login --username "$(printenv GITLAB_USERNAME)" --password "$(printenv GITLAB_PASSWORD)" registry.styleschool.ru

  script:
    - docker pull "$(printenv GITLAB_REPOSITORY):latest"
    - docker run --detach
      --env "HOST=$(printenv ROOT_URL)"
      --env "PORT=4858"
      --name "$(printenv CONTAINER_NAME)"
      --publish $(printenv PORT):4858
      --restart=always
      "$(printenv GITLAB_REPOSITORY):latest"
